"""Phase 3 — deterministic lowering: V-AIR (or P-AIR with a schedule) -> AscendC.

No probabilistic reasoning. Given a CHECKED AIR and a schedule (block_dim, tile_len,
buffer_num), emit a complete, self-contained AscendC kernel-launch project for the
target (Ascend310P1): the device kernel, a differential-test host harness (generates
inputs, computes a scalar oracle on the host, runs + times the kernel, reports SPR and
throughput), and the CMakeLists. Identical (AIR, sched) -> identical code.
"""
from dataclasses import dataclass
from .air import AIR, Pattern
from .guard import guard


@dataclass(frozen=True)
class Sched:
    block_dim: int = 8       # AI cores used
    tile_len: int = 1024     # elements per UB tile (MAP/REDUCE)
    buffer_num: int = 2      # double buffering
    # GEMV/GEMM tiling
    tile_m: int = 64
    tile_n: int = 64
    tile_k: int = 64

    def tag(self) -> str:
        return f"b{self.block_dim}_t{self.tile_len}_q{self.buffer_num}"


# ---------------------------------------------------------------------------
def map_kind(air: AIR) -> str:
    """Classify a MAP elem_op into {copy, scal, axpy} deterministically."""
    e = air.s_algo.elem_op
    if e.op == "load":
        return "copy"
    if e.op == "mulc":
        return "scal"
    if e.op == "add":
        return "axpy"
    raise ValueError(f"unsupported MAP elem_op {e.op}")


CMAKE = """cmake_minimum_required(VERSION 3.16)
project(ascendc_op)
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE "Release" CACHE STRING "build type" FORCE)
endif()
set(RUN_MODE "npu" CACHE STRING "run mode")
set(SOC_VERSION "Ascend310P1" CACHE STRING "soc")
set(ASCEND_CANN_PACKAGE_PATH "/usr/local/Ascend/ascend-toolkit/latest" CACHE PATH "cann")
if(CMAKE_INSTALL_PREFIX STREQUAL "/usr/local")
    set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/out" CACHE PATH "" FORCE)
endif()
if(EXISTS ${ASCEND_CANN_PACKAGE_PATH}/compiler/tikcpp/ascendc_kernel_cmake)
    set(ASCENDC_CMAKE_DIR ${ASCEND_CANN_PACKAGE_PATH}/compiler/tikcpp/ascendc_kernel_cmake)
elseif(EXISTS ${ASCEND_CANN_PACKAGE_PATH}/tools/tikcpp/ascendc_kernel_cmake)
    set(ASCENDC_CMAKE_DIR ${ASCEND_CANN_PACKAGE_PATH}/tools/tikcpp/ascendc_kernel_cmake)
else()
    set(ASCENDC_CMAKE_DIR ${ASCEND_CANN_PACKAGE_PATH}/aarch64-linux/tikcpp/ascendc_kernel_cmake)
endif()
include(${ASCENDC_CMAKE_DIR}/ascendc.cmake)
ascendc_library(ascendc_kernels_${RUN_MODE} STATIC %KERNEL%.cpp)
add_executable(%EXE% main.cpp)
target_compile_options(%EXE% PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-std=c++17>)
target_include_directories(%EXE% PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${ASCEND_CANN_PACKAGE_PATH}/runtime/include)
target_link_libraries(%EXE% PRIVATE $<BUILD_INTERFACE:host_intf_pub> ascendc_kernels_${RUN_MODE} ascendcl c_sec runtime stdc++ m)
"""


# ---------------------------------------------------------------------------
def emit_map_kernel(air: AIR, sched: Sched) -> str:
    kind = map_kind(air)
    name = air.name
    needs_y = (kind == "axpy")
    compute = {
        "copy": "        Adds(oL, xL, (float)0.0, this->tileLen);\n",
        "scal": "        Muls(oL, xL, this->alpha, this->tileLen);\n",
        "axpy": ("        Muls(oL, xL, this->alpha, this->tileLen);\n"
                 "        Add(oL, oL, yL, this->tileLen);\n"),
    }[kind]
    y_init = "        yGm.SetGlobalBuffer((__gm__ float*)y + this->blockLen * GetBlockIdx(), this->blockLen);\n" if True else ""
    y_qinit = "        pipe.InitBuffer(qy, BUFNUM, this->tileLen * sizeof(float));\n" if needs_y else ""
    y_copyin = ("        LocalTensor<float> yL = qy.AllocTensor<float>();\n"
                "        DataCopy(yL, yGm[progress * this->tileLen], this->tileLen);\n"
                "        qy.EnQue(yL);\n") if needs_y else ""
    y_deque = "        LocalTensor<float> yL = qy.DeQue<float>();\n" if needs_y else ""
    y_free = "        qy.FreeTensor(yL);\n" if needs_y else ""
    return f"""// AUTO-GENERATED by ascend_lower.py from CHECKED AIR ({name}, MAP/{kind}); sched={sched.tag()}
#include "kernel_operator.h"
using namespace AscendC;
constexpr int32_t BUFNUM = {sched.buffer_num};
constexpr int32_t TILELEN = {sched.tile_len};

class KMap {{
public:
    __aicore__ inline KMap() {{}}
    __aicore__ inline void Init(GM_ADDR x, GM_ADDR y, GM_ADDR out, float alpha, uint32_t total) {{
        this->blockLen = total / GetBlockNum();
        this->tileLen = TILELEN;
        this->numTile = this->blockLen / this->tileLen;
        this->alpha = alpha;
        xGm.SetGlobalBuffer((__gm__ float*)x + this->blockLen * GetBlockIdx(), this->blockLen);
{y_init}        outGm.SetGlobalBuffer((__gm__ float*)out + this->blockLen * GetBlockIdx(), this->blockLen);
        pipe.InitBuffer(qx, BUFNUM, this->tileLen * sizeof(float));
{y_qinit}        pipe.InitBuffer(qo, BUFNUM, this->tileLen * sizeof(float));
    }}
    __aicore__ inline void Process() {{
        for (uint32_t i = 0; i < this->numTile; i++) {{ CopyIn(i); Compute(i); CopyOut(i); }}
    }}
private:
    __aicore__ inline void CopyIn(uint32_t progress) {{
        LocalTensor<float> xL = qx.AllocTensor<float>();
        DataCopy(xL, xGm[progress * this->tileLen], this->tileLen);
        qx.EnQue(xL);
{y_copyin}    }}
    __aicore__ inline void Compute(uint32_t progress) {{
        LocalTensor<float> xL = qx.DeQue<float>();
{y_deque}        LocalTensor<float> oL = qo.AllocTensor<float>();
{compute}        qo.EnQue<float>(oL);
        qx.FreeTensor(xL);
{y_free}    }}
    __aicore__ inline void CopyOut(uint32_t progress) {{
        LocalTensor<float> oL = qo.DeQue<float>();
        DataCopy(outGm[progress * this->tileLen], oL, this->tileLen);
        qo.FreeTensor(oL);
    }}
    TPipe pipe;
    TQue<QuePosition::VECIN, BUFNUM> qx, qy;
    TQue<QuePosition::VECOUT, BUFNUM> qo;
    GlobalTensor<float> xGm, yGm, outGm;
    uint32_t blockLen, tileLen, numTile; float alpha;
}};

extern "C" __global__ __aicore__ void {name}(GM_ADDR x, GM_ADDR y, GM_ADDR out, float alpha, uint32_t total) {{
    KMap op; op.Init(x, y, out, alpha, total); op.Process();
}}
"""


def emit_reduce_kernel(air: AIR, sched: Sched) -> str:
    """REDUCE: each core accumulates its chunk elementwise into a UB accumulator, then a
    single ReduceSum yields the core partial -> partials[blockIdx]. Host sums partials
    and applies post (sqrt for nrm2). pre in {a, ab, abs_a, aa}."""
    name = air.name
    pre = air.s_algo.reduce_pre
    needs_y = (pre == "ab")
    precompute = {
        "a":     "        Adds(pL, xL, (float)0.0, this->tileLen);\n",
        "ab":    "        Mul(pL, xL, yL, this->tileLen);\n",
        "abs_a": "        Abs(pL, xL, this->tileLen);\n",
        "aa":    "        Mul(pL, xL, xL, this->tileLen);\n",
    }[pre]
    y_init = "        yGm.SetGlobalBuffer((__gm__ float*)y + this->blockLen * GetBlockIdx(), this->blockLen);\n"
    y_qinit = "        pipe.InitBuffer(qy, BUFNUM, this->tileLen * sizeof(float));\n" if needs_y else ""
    y_copyin = ("        LocalTensor<float> yL = qy.AllocTensor<float>();\n"
                "        DataCopy(yL, yGm[progress * this->tileLen], this->tileLen);\n"
                "        qy.EnQue(yL);\n") if needs_y else ""
    y_deque = "        LocalTensor<float> yL = qy.DeQue<float>();\n" if needs_y else ""
    y_free = "        qy.FreeTensor(yL);\n" if needs_y else ""
    # Each block writes its partial into a 32B-aligned 8-float slot (partials[blockIdx*8]);
    # avoids unaligned 1-element GM DataCopy. Host sums partials[b*8] over blocks.
    return f"""// AUTO-GENERATED by ascend_lower.py from CHECKED AIR ({name}, REDUCE sum/pre={pre}); sched={sched.tag()}
#include "kernel_operator.h"
using namespace AscendC;
constexpr int32_t BUFNUM = {sched.buffer_num};
constexpr int32_t TILELEN = {sched.tile_len};

class KReduce {{
public:
    __aicore__ inline KReduce() {{}}
    __aicore__ inline void Init(GM_ADDR x, GM_ADDR y, GM_ADDR partials, uint32_t total) {{
        this->blockLen = total / GetBlockNum();
        this->tileLen = TILELEN;
        this->numTile = this->blockLen / this->tileLen;
        xGm.SetGlobalBuffer((__gm__ float*)x + this->blockLen * GetBlockIdx(), this->blockLen);
{y_init}        partGm.SetGlobalBuffer((__gm__ float*)partials + GetBlockIdx() * 8, 8);
        pipe.InitBuffer(qx, BUFNUM, this->tileLen * sizeof(float));
{y_qinit}        pipe.InitBuffer(preBuf, this->tileLen * sizeof(float));
        pipe.InitBuffer(accBuf, this->tileLen * sizeof(float));
        pipe.InitBuffer(workBuf, this->tileLen * sizeof(float));
        pipe.InitBuffer(sumBuf, 32);  // 8 floats (32B aligned)
    }}
    __aicore__ inline void Process() {{
        LocalTensor<float> acc = accBuf.Get<float>();
        LocalTensor<float> pL = preBuf.Get<float>();
        Duplicate(acc, (float)0.0, this->tileLen);
        for (uint32_t i = 0; i < this->numTile; i++) {{
            CopyIn(i);
            LocalTensor<float> xL = qx.DeQue<float>();
{y_deque}{precompute}            Add(acc, acc, pL, this->tileLen);
            qx.FreeTensor(xL);
{y_free}        }}
        LocalTensor<float> work = workBuf.Get<float>();
        LocalTensor<float> s = sumBuf.Get<float>();
        Duplicate(s, (float)0.0, 8);
        ReduceSum<float>(s, acc, work, this->tileLen);
        DataCopy(partGm, s, 8);
    }}
private:
    __aicore__ inline void CopyIn(uint32_t progress) {{
        LocalTensor<float> xL = qx.AllocTensor<float>();
        DataCopy(xL, xGm[progress * this->tileLen], this->tileLen);
        qx.EnQue(xL);
{y_copyin}    }}
    TPipe pipe;
    TQue<QuePosition::VECIN, BUFNUM> qx, qy;
    TBuf<QuePosition::VECCALC> preBuf, accBuf, workBuf, sumBuf;
    GlobalTensor<float> xGm, yGm, partGm;
    uint32_t blockLen, tileLen, numTile;
}};

extern "C" __global__ __aicore__ void {name}(GM_ADDR x, GM_ADDR y, GM_ADDR partials, uint32_t total) {{
    KReduce op; op.Init(x, y, partials, total); op.Process();
}}
"""


def emit_gemv_kernel(air: AIR, sched: Sched) -> str:
    """GEMV: y = alpha*A*x + beta*y. Parallel over rows (map_i); each row is an inner
    product over n (contract_j) realized with Mul + ReduceSum. A row-major. Rows split
    across cores; x held resident in UB; per-row result placed via scalar SetValue."""
    name = air.name
    return f"""// AUTO-GENERATED by ascend_lower.py from CHECKED AIR ({name}, GEMV); sched={sched.tag()}
#include "kernel_operator.h"
using namespace AscendC;

// Per-row inner product (Mul + ReduceSum) into a UB 'dots' vector via one scalar
// placement per row (guarded by V_S/S_V cross-pipe sync), then a fully-vectorized
// y = alpha*dots + beta*y combine. A is row-major; rows split across cores.
class KGemv {{
public:
    __aicore__ inline KGemv() {{}}
    __aicore__ inline void Init(GM_ADDR A, GM_ADDR x, GM_ADDR y, float alpha, float beta,
                                uint32_t m, uint32_t n) {{
        this->n = n;
        this->rows = m / GetBlockNum();
        this->alpha = alpha; this->beta = beta;
        uint32_t base = this->rows * GetBlockIdx();
        aGm.SetGlobalBuffer((__gm__ float*)A + (uint64_t)base * n, (uint64_t)this->rows * n);
        xGm.SetGlobalBuffer((__gm__ float*)x, n);
        yGm.SetGlobalBuffer((__gm__ float*)y + base, this->rows);
        pipe.InitBuffer(qa, 2, n * sizeof(float));
        pipe.InitBuffer(xBuf, n * sizeof(float));
        pipe.InitBuffer(preBuf, n * sizeof(float));
        pipe.InitBuffer(accBuf, 64 * sizeof(float));   // row partial accumulator (1 repeat)
        pipe.InitBuffer(workBuf, 64 * sizeof(float));
        pipe.InitBuffer(dotBuf, 32);
        pipe.InitBuffer(dotsBuf, this->rows * sizeof(float));
        pipe.InitBuffer(yldBuf, this->rows * sizeof(float));
        pipe.InitBuffer(youtBuf, this->rows * sizeof(float));
        pipe.InitBuffer(tmpBuf, this->rows * sizeof(float));
    }}
    __aicore__ inline void Process() {{
        LocalTensor<float> x = xBuf.Get<float>();
        DataCopy(x, xGm, this->n);
        SetFlag<HardEvent::MTE2_V>(EVENT_ID0); WaitFlag<HardEvent::MTE2_V>(EVENT_ID0);
        LocalTensor<float> pre = preBuf.Get<float>();
        LocalTensor<float> acc = accBuf.Get<float>();
        LocalTensor<float> work = workBuf.Get<float>();
        LocalTensor<float> dot = dotBuf.Get<float>();
        LocalTensor<float> dots = dotsBuf.Get<float>();
        uint32_t chunks = this->n / 64;
        for (uint32_t r = 0; r < this->rows; r++) {{
            LocalTensor<float> aL = qa.AllocTensor<float>();
            DataCopy(aL, aGm[(uint64_t)r * this->n], this->n); qa.EnQue(aL); aL = qa.DeQue<float>();
            Mul(pre, aL, x, this->n);                         // products A[r,:]*x
            Duplicate(acc, (float)0.0, 64);
            for (uint32_t c = 0; c < chunks; c++)             // fold n products into 64 lanes
                Add(acc, acc, pre[c * 64], 64);
            Duplicate(dot, (float)0.0, 8);
            ReduceSum<float>(dot, acc, work, 64);             // single-repeat reduce (reliable)
            qa.FreeTensor(aL);
            SetFlag<HardEvent::V_S>(EVENT_ID1); WaitFlag<HardEvent::V_S>(EVENT_ID1);
            dots.SetValue(r, dot.GetValue(0));
            SetFlag<HardEvent::S_V>(EVENT_ID2); WaitFlag<HardEvent::S_V>(EVENT_ID2);
        }}
        LocalTensor<float> yld = yldBuf.Get<float>();
        LocalTensor<float> yout = youtBuf.Get<float>();
        LocalTensor<float> tmp = tmpBuf.Get<float>();
        DataCopy(yld, yGm, this->rows);
        SetFlag<HardEvent::MTE2_V>(EVENT_ID0); WaitFlag<HardEvent::MTE2_V>(EVENT_ID0);
        Muls(yout, dots, this->alpha, this->rows);   // yout = alpha*dots
        Muls(tmp, yld, this->beta, this->rows);      // tmp  = beta*y_old
        Add(yout, yout, tmp, this->rows);            // yout = alpha*dots + beta*y
        SetFlag<HardEvent::V_MTE3>(EVENT_ID0); WaitFlag<HardEvent::V_MTE3>(EVENT_ID0);
        DataCopy(yGm, yout, this->rows);
    }}
private:
    TPipe pipe;
    TQue<QuePosition::VECIN, 2> qa;
    TBuf<QuePosition::VECCALC> xBuf, preBuf, accBuf, workBuf, dotBuf, dotsBuf, yldBuf, youtBuf, tmpBuf;
    GlobalTensor<float> aGm, xGm, yGm;
    uint32_t n, rows; float alpha, beta;
}};

extern "C" __global__ __aicore__ void {name}(GM_ADDR A, GM_ADDR x, GM_ADDR y,
        float alpha, float beta, uint32_t m, uint32_t n) {{
    KGemv op; op.Init(A, x, y, alpha, beta, m, n); op.Process();
}}
"""


def emit_gemm_kernel(air: AIR, sched: Sched) -> str:
    """GEMM: C = alpha*A*B + beta*C (row-major). Parallel over rows of C. Each output row
    is built by rank-1 accumulation C[i,:] += A[i,k]*B[k,:] over k (B rows are contiguous),
    realized with Muls+Add (no reduction => sidesteps the large-count ReduceSum quirk).
    The contracted scalar A[i,k] is read once per (i,k) from the resident A row."""
    name = air.name
    return f"""// AUTO-GENERATED by ascend_lower.py from CHECKED AIR ({name}, GEMM); sched={sched.tag()}
#include "kernel_operator.h"
using namespace AscendC;

class KGemm {{
public:
    __aicore__ inline KGemm() {{}}
    __aicore__ inline void Init(GM_ADDR A, GM_ADDR B, GM_ADDR C, float alpha, float beta,
                                uint32_t m, uint32_t n, uint32_t k) {{
        this->n = n; this->k = k; this->rows = m / GetBlockNum();
        this->alpha = alpha; this->beta = beta;
        uint32_t base = this->rows * GetBlockIdx();
        aGm.SetGlobalBuffer((__gm__ float*)A + (uint64_t)base * k, (uint64_t)this->rows * k);
        bGm.SetGlobalBuffer((__gm__ float*)B, (uint64_t)k * n);
        cGm.SetGlobalBuffer((__gm__ float*)C + (uint64_t)base * n, (uint64_t)this->rows * n);
        pipe.InitBuffer(qb, 2, n * sizeof(float));
        pipe.InitBuffer(aRowBuf, k * sizeof(float));
        pipe.InitBuffer(caccBuf, n * sizeof(float));
        pipe.InitBuffer(coldBuf, n * sizeof(float));
        pipe.InitBuffer(tmpBuf, n * sizeof(float));
    }}
    __aicore__ inline void Process() {{
        LocalTensor<float> aRow = aRowBuf.Get<float>();
        LocalTensor<float> cacc = caccBuf.Get<float>();
        LocalTensor<float> cold = coldBuf.Get<float>();
        LocalTensor<float> tmp = tmpBuf.Get<float>();
        for (uint32_t r = 0; r < this->rows; r++) {{
            DataCopy(aRow, aGm[(uint64_t)r * this->k], this->k);     // A[i,:] resident for scalar reads
            SetFlag<HardEvent::MTE2_S>(EVENT_ID0); WaitFlag<HardEvent::MTE2_S>(EVENT_ID0);
            Duplicate(cacc, (float)0.0, this->n);
            for (uint32_t kk = 0; kk < this->k; kk++) {{
                LocalTensor<float> bL = qb.AllocTensor<float>();
                DataCopy(bL, bGm[(uint64_t)kk * this->n], this->n); qb.EnQue(bL); bL = qb.DeQue<float>();
                float aik = aRow.GetValue(kk);
                Muls(tmp, bL, aik, this->n);                          // tmp = A[i,k]*B[k,:]
                Add(cacc, cacc, tmp, this->n);                        // cacc += tmp
                qb.FreeTensor(bL);
            }}
            DataCopy(cold, cGm[(uint64_t)r * this->n], this->n);
            SetFlag<HardEvent::MTE2_V>(EVENT_ID1); WaitFlag<HardEvent::MTE2_V>(EVENT_ID1);
            Muls(cacc, cacc, this->alpha, this->n);                   // alpha*sum
            Muls(cold, cold, this->beta, this->n);                    // beta*C_old
            Add(cacc, cacc, cold, this->n);
            SetFlag<HardEvent::V_MTE3>(EVENT_ID2); WaitFlag<HardEvent::V_MTE3>(EVENT_ID2);
            DataCopy(cGm[(uint64_t)r * this->n], cacc, this->n);
            // cross-row: C write (MTE3) must finish reading cacc before next row reuses it (V),
            // and before next row's input loads (MTE2).
            SetFlag<HardEvent::MTE3_V>(EVENT_ID2); WaitFlag<HardEvent::MTE3_V>(EVENT_ID2);
            SetFlag<HardEvent::MTE3_MTE2>(EVENT_ID3); WaitFlag<HardEvent::MTE3_MTE2>(EVENT_ID3);
        }}
    }}
private:
    TPipe pipe;
    TQue<QuePosition::VECIN, 2> qb;
    TBuf<QuePosition::VECCALC> aRowBuf, caccBuf, coldBuf, tmpBuf;
    GlobalTensor<float> aGm, bGm, cGm;
    uint32_t n, k, rows; float alpha, beta;
}};

extern "C" __global__ __aicore__ void {name}(GM_ADDR A, GM_ADDR B, GM_ADDR C,
        float alpha, float beta, uint32_t m, uint32_t n, uint32_t k) {{
    KGemm op; op.Init(A, B, C, alpha, beta, m, n, k); op.Process();
}}
"""


def emit_gemm_nt_kernel(air: AIR, sched: Sched) -> str:
    """GEMM-NT / SYRK: C = alpha*A*B^T + beta*C (SYRK: B=A). C[i,j] = dot(A[i,:], B[j,:]) —
    BOTH operands are contiguous rows (row-major), so no transpose/stride needed. Parallel
    over rows of C; each output element is an inner product over k (64-lane fold + reduce);
    the row is combined with beta*C vectorized. Distinct from the NN gemm (rank-1) form."""
    name = air.name
    return f"""// AUTO-GENERATED by ascend_lower.py from CHECKED AIR ({name}, {air.s_algo.pattern.value}, row-dot); sched={sched.tag()}
#include "kernel_operator.h"
using namespace AscendC;

class KGemmNT {{
public:
    __aicore__ inline KGemmNT() {{}}
    __aicore__ inline void Init(GM_ADDR A, GM_ADDR B, GM_ADDR C, float alpha, float beta,
                                uint32_t m, uint32_t n, uint32_t k) {{
        this->n = n; this->k = k; this->rows = m / GetBlockNum();
        this->alpha = alpha; this->beta = beta;
        uint32_t base = this->rows * GetBlockIdx();
        aGm.SetGlobalBuffer((__gm__ float*)A + (uint64_t)base * k, (uint64_t)this->rows * k);
        bGm.SetGlobalBuffer((__gm__ float*)B, (uint64_t)n * k);
        cGm.SetGlobalBuffer((__gm__ float*)C + (uint64_t)base * n, (uint64_t)this->rows * n);
        pipe.InitBuffer(qb, 2, k * sizeof(float));
        pipe.InitBuffer(aRowBuf, k * sizeof(float));
        pipe.InitBuffer(preBuf, k * sizeof(float));
        pipe.InitBuffer(accBuf, 64 * sizeof(float));
        pipe.InitBuffer(workBuf, 64 * sizeof(float));
        pipe.InitBuffer(dotBuf, 32);
        pipe.InitBuffer(cRowBuf, n * sizeof(float));
        pipe.InitBuffer(coldBuf, n * sizeof(float));
        pipe.InitBuffer(tmpBuf, n * sizeof(float));
    }}
    __aicore__ inline void Process() {{
        LocalTensor<float> aRow = aRowBuf.Get<float>();
        LocalTensor<float> pre = preBuf.Get<float>();
        LocalTensor<float> acc = accBuf.Get<float>();
        LocalTensor<float> work = workBuf.Get<float>();
        LocalTensor<float> dot = dotBuf.Get<float>();
        LocalTensor<float> cRow = cRowBuf.Get<float>();
        LocalTensor<float> cold = coldBuf.Get<float>();
        LocalTensor<float> tmp = tmpBuf.Get<float>();
        uint32_t chunks = this->k / 64;
        for (uint32_t r = 0; r < this->rows; r++) {{
            DataCopy(aRow, aGm[(uint64_t)r * this->k], this->k);
            SetFlag<HardEvent::MTE2_V>(EVENT_ID0); WaitFlag<HardEvent::MTE2_V>(EVENT_ID0);
            for (uint32_t j = 0; j < this->n; j++) {{
                LocalTensor<float> bL = qb.AllocTensor<float>();
                DataCopy(bL, bGm[(uint64_t)j * this->k], this->k); qb.EnQue(bL); bL = qb.DeQue<float>();
                Mul(pre, aRow, bL, this->k);
                Duplicate(acc, (float)0.0, 64);
                for (uint32_t c = 0; c < chunks; c++) Add(acc, acc, pre[c * 64], 64);
                Duplicate(dot, (float)0.0, 8);
                ReduceSum<float>(dot, acc, work, 64);
                qb.FreeTensor(bL);
                SetFlag<HardEvent::V_S>(EVENT_ID1); WaitFlag<HardEvent::V_S>(EVENT_ID1);
                cRow.SetValue(j, dot.GetValue(0));
                SetFlag<HardEvent::S_V>(EVENT_ID2); WaitFlag<HardEvent::S_V>(EVENT_ID2);
            }}
            DataCopy(cold, cGm[(uint64_t)r * this->n], this->n);
            SetFlag<HardEvent::MTE2_V>(EVENT_ID0); WaitFlag<HardEvent::MTE2_V>(EVENT_ID0);
            Muls(cRow, cRow, this->alpha, this->n);
            Muls(cold, cold, this->beta, this->n);
            Add(cRow, cRow, cold, this->n);
            SetFlag<HardEvent::V_MTE3>(EVENT_ID2); WaitFlag<HardEvent::V_MTE3>(EVENT_ID2);
            DataCopy(cGm[(uint64_t)r * this->n], cRow, this->n);
            SetFlag<HardEvent::MTE3_V>(EVENT_ID2); WaitFlag<HardEvent::MTE3_V>(EVENT_ID2);
            SetFlag<HardEvent::MTE3_MTE2>(EVENT_ID3); WaitFlag<HardEvent::MTE3_MTE2>(EVENT_ID3);
        }}
    }}
private:
    TPipe pipe;
    TQue<QuePosition::VECIN, 2> qb;
    TBuf<QuePosition::VECCALC> aRowBuf, preBuf, accBuf, workBuf, dotBuf, cRowBuf, coldBuf, tmpBuf;
    GlobalTensor<float> aGm, bGm, cGm;
    uint32_t n, k, rows; float alpha, beta;
}};

extern "C" __global__ __aicore__ void {name}(GM_ADDR A, GM_ADDR B, GM_ADDR C,
        float alpha, float beta, uint32_t m, uint32_t n, uint32_t k) {{
    KGemmNT op; op.Init(A, B, C, alpha, beta, m, n, k); op.Process();
}}
"""


# ---------------------------------------------------------------------------
# Host differential-test harness (the independent oracle + perf measurement).
def _map_ref_expr(kind: str) -> str:
    return {"copy": "xh[i]", "scal": "alpha*xh[i]", "axpy": "alpha*xh[i]+yh[i]"}[kind]

def _map_bytes(kind: str) -> str:
    return {"copy": "2.0", "scal": "2.0", "axpy": "3.0"}[kind]

def _reduce_pre_ref(pre: str) -> str:
    return {"a": "xh[i]", "ab": "xh[i]*yh[i]", "abs_a": "fabs(xh[i])", "aa": "xh[i]*xh[i]"}[pre]


def _legacy_host(air: AIR, sched: Sched) -> str:
    name = air.name
    p = air.s_algo.pattern
    if p == Pattern.MAP:
        kind = map_kind(air)
        ref = _map_ref_expr(kind); nbytes = _map_bytes(kind)
        rtol = "1e-5"
        return f"""// AUTO-GENERATED differential-test harness for {name} (MAP/{kind})
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cmath>
#include <chrono>
#include "acl/acl.h"
#include "aclrtlaunch_{name}.h"
#define CK(x) do{{aclError e=(x); if(e!=ACL_SUCCESS){{printf("ACLERR %d @%d\\n",e,__LINE__);return 2;}}}}while(0)
int main(int argc,char**argv){{
    uint32_t n = (argc>1)?(uint32_t)atol(argv[1]):(1u<<20);
    int iters = (argc>2)?atoi(argv[2]):50;
    const uint32_t blockDim = {sched.block_dim};
    n = (n/(blockDim*{sched.tile_len}))*(blockDim*{sched.tile_len}); if(n==0)n=blockDim*{sched.tile_len};
    float alpha=1.5f; size_t bytes=(size_t)n*sizeof(float);
    float*xh=(float*)malloc(bytes),*yh=(float*)malloc(bytes),*oh=(float*)malloc(bytes);
    for(uint32_t i=0;i<n;i++){{xh[i]=(float)((int)(i%17)-8)*0.125f; yh[i]=(float)((int)(i%13)-6)*0.25f;}}
    CK(aclInit(nullptr)); CK(aclrtSetDevice(0)); aclrtStream st; CK(aclrtCreateStream(&st));
    void*xd,*yd,*od; CK(aclrtMalloc(&xd,bytes,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMalloc(&yd,bytes,ACL_MEM_MALLOC_HUGE_FIRST)); CK(aclrtMalloc(&od,bytes,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMemcpy(xd,bytes,xh,bytes,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(aclrtMemcpy(yd,bytes,yh,bytes,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,xd,yd,od,alpha,n)); CK(aclrtSynchronizeStream(st)); // warmup
    auto t0=std::chrono::high_resolution_clock::now();
    for(int it=0;it<iters;it++) CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,xd,yd,od,alpha,n));
    CK(aclrtSynchronizeStream(st));
    auto t1=std::chrono::high_resolution_clock::now();
    double us=std::chrono::duration<double,std::micro>(t1-t0).count()/iters;
    CK(aclrtMemcpy(oh,bytes,od,bytes,ACL_MEMCPY_DEVICE_TO_HOST));
    double maxrel=0; for(uint32_t i=0;i<n;i++){{double r={ref}; double e=fabs((double)oh[i]-r)/(fabs(r)+1e-12); if(e>maxrel)maxrel=e;}}
    double gbps={nbytes}*(double)n*sizeof(float)/(us*1e-6)/1e9;
    int pass = maxrel < {rtol};
    printf("RESULT op={name} pattern=map n=%u maxrel=%.3e pass=%d us=%.3f GBps=%.2f\\n",n,maxrel,pass,us,gbps);
    aclrtFree(xd);aclrtFree(yd);aclrtFree(od);free(xh);free(yh);free(oh);
    aclrtDestroyStream(st);aclrtResetDevice(0);aclFinalize(); return pass?0:1;
}}
"""
    if p == Pattern.REDUCE:
        pre = air.s_algo.reduce_pre; post = air.s_algo.reduce_post
        needs_y = (pre == "ab")
        preref = _reduce_pre_ref(pre)
        postref = "sqrt(acc)" if post == "sqrt" else "acc"
        nbytes = "2.0" if needs_y else "1.0"
        ycopy = "    CK(aclrtMemcpy(yd,bytes,yh,bytes,ACL_MEMCPY_HOST_TO_DEVICE));\n"
        return f"""// AUTO-GENERATED differential-test harness for {name} (REDUCE sum/pre={pre}{'/sqrt' if post=='sqrt' else ''})
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cmath>
#include <chrono>
#include "acl/acl.h"
#include "aclrtlaunch_{name}.h"
#define CK(x) do{{aclError e=(x); if(e!=ACL_SUCCESS){{printf("ACLERR %d @%d\\n",e,__LINE__);return 2;}}}}while(0)
int main(int argc,char**argv){{
    uint32_t n=(argc>1)?(uint32_t)atol(argv[1]):(1u<<20);
    int iters=(argc>2)?atoi(argv[2]):50;
    const uint32_t blockDim={sched.block_dim};
    n=(n/(blockDim*{sched.tile_len}))*(blockDim*{sched.tile_len}); if(n==0)n=blockDim*{sched.tile_len};
    size_t bytes=(size_t)n*sizeof(float);
    float*xh=(float*)malloc(bytes),*yh=(float*)malloc(bytes);
    for(uint32_t i=0;i<n;i++){{xh[i]=(float)((int)(i%17)-8)*0.0625f; yh[i]=(float)((int)(i%13)-6)*0.125f;}}
    CK(aclInit(nullptr)); CK(aclrtSetDevice(0)); aclrtStream st; CK(aclrtCreateStream(&st));
    void*xd,*yd,*pd; size_t pbytes=(size_t)blockDim*8*sizeof(float);
    CK(aclrtMalloc(&xd,bytes,ACL_MEM_MALLOC_HUGE_FIRST)); CK(aclrtMalloc(&yd,bytes,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMalloc(&pd,pbytes,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMemcpy(xd,bytes,xh,bytes,ACL_MEMCPY_HOST_TO_DEVICE));
{ycopy if needs_y else ''}    CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,xd,yd,pd,n)); CK(aclrtSynchronizeStream(st)); // warmup
    auto t0=std::chrono::high_resolution_clock::now();
    for(int it=0;it<iters;it++) CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,xd,yd,pd,n));
    CK(aclrtSynchronizeStream(st));
    auto t1=std::chrono::high_resolution_clock::now();
    double us=std::chrono::duration<double,std::micro>(t1-t0).count()/iters;
    float*ph=(float*)malloc(pbytes); CK(aclrtMemcpy(ph,pbytes,pd,pbytes,ACL_MEMCPY_DEVICE_TO_HOST));
    double dev=0; for(uint32_t b=0;b<blockDim;b++) dev+=ph[b*8]; double devr=({ 'sqrt(dev)' if post=='sqrt' else 'dev'});
    double acc=0; for(uint32_t i=0;i<n;i++) acc+={preref}; double ref={postref};
    double maxrel=fabs(devr-ref)/(fabs(ref)+1e-12);
    double gbps={nbytes}*(double)n*sizeof(float)/(us*1e-6)/1e9;
    int pass = maxrel < 1e-3;
    printf("RESULT op={name} pattern=reduce n=%u maxrel=%.3e pass=%d us=%.3f GBps=%.2f\\n",n,maxrel,pass,us,gbps);
    aclrtFree(xd);aclrtFree(yd);aclrtFree(pd);free(xh);free(yh);free(ph);
    aclrtDestroyStream(st);aclrtResetDevice(0);aclFinalize(); return pass?0:1;
}}
"""
    if p == Pattern.GEMV:
        return f"""// AUTO-GENERATED differential-test harness for {name} (GEMV)
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cmath>
#include <chrono>
#include "acl/acl.h"
#include "aclrtlaunch_{name}.h"
#define CK(x) do{{aclError e=(x); if(e!=ACL_SUCCESS){{printf("ACLERR %d @%d\\n",e,__LINE__);return 2;}}}}while(0)
int main(int argc,char**argv){{
    uint32_t m=(argc>1)?(uint32_t)atol(argv[1]):1024;
    uint32_t n=(argc>2)?(uint32_t)atol(argv[2]):1024;
    int iters=(argc>3)?atoi(argv[3]):50;
    const uint32_t blockDim={sched.block_dim};
    if(n%64) n=(n/64)*64; if(n==0)n=64;                 // inner reduce folds in 64-lanes
    if((m/blockDim)%8){{ m=((m/blockDim)/8*8)*blockDim; }} if(m==0)m=blockDim*8;  // rows/core mult of 8
    float alpha=1.25f, beta=0.5f;
    size_t Ab=(size_t)m*n*sizeof(float), xb=(size_t)n*sizeof(float), yb=(size_t)m*sizeof(float);
    float*Ah=(float*)malloc(Ab),*xh=(float*)malloc(xb),*yh=(float*)malloc(yb),*yo=(float*)malloc(yb);
    for(size_t i=0;i<(size_t)m*n;i++) Ah[i]=(float)((int)(i%13)-6)*0.05f;
    for(uint32_t j=0;j<n;j++) xh[j]=(float)((int)(j%7)-3)*0.1f;
    for(uint32_t i=0;i<m;i++){{ yh[i]=(float)((int)(i%5)-2)*0.2f; yo[i]=yh[i]; }}
    CK(aclInit(nullptr)); CK(aclrtSetDevice(0)); aclrtStream st; CK(aclrtCreateStream(&st));
    void*Ad,*xd,*yd; CK(aclrtMalloc(&Ad,Ab,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMalloc(&xd,xb,ACL_MEM_MALLOC_HUGE_FIRST)); CK(aclrtMalloc(&yd,yb,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMemcpy(Ad,Ab,Ah,Ab,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(aclrtMemcpy(xd,xb,xh,xb,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(aclrtMemcpy(yd,yb,yh,yb,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,Ad,xd,yd,alpha,beta,m,n)); CK(aclrtSynchronizeStream(st));
    CK(aclrtMemcpy(yh,yb,yd,yb,ACL_MEMCPY_DEVICE_TO_HOST)); // correctness on fresh y
    double maxabs=0, maxref=0; for(uint32_t i=0;i<m;i++){{ double s=0; for(uint32_t j=0;j<n;j++) s+=(double)Ah[i*n+j]*xh[j];
        double r=alpha*s+beta*(double)yo[i]; double e=fabs((double)yh[i]-r);
        if(e>maxabs)maxabs=e; if(fabs(r)>maxref)maxref=fabs(r); }}
    double maxrel=maxabs/(maxref+1e-9);  // norm-wise rel error (gemv has near-zero rows)
    CK(aclrtMemcpy(yd,yb,yo,yb,ACL_MEMCPY_HOST_TO_DEVICE)); // reset y for timing
    auto t0=std::chrono::high_resolution_clock::now();
    for(int it=0;it<iters;it++) CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,Ad,xd,yd,alpha,beta,m,n));
    CK(aclrtSynchronizeStream(st));
    auto t1=std::chrono::high_resolution_clock::now();
    double us=std::chrono::duration<double,std::micro>(t1-t0).count()/iters;
    double gflops=2.0*(double)m*n/(us*1e-6)/1e9;
    double gbps=((double)m*n+ n + m)*sizeof(float)/(us*1e-6)/1e9;
    int pass = maxrel < 2e-3;
    printf("RESULT op={name} pattern=gemv n=%u m=%u maxrel=%.3e pass=%d us=%.3f GFLOPs=%.2f GBps=%.2f\\n",
           n,m,maxrel,pass,us,gflops,gbps);
    aclrtFree(Ad);aclrtFree(xd);aclrtFree(yd);free(Ah);free(xh);free(yh);free(yo);
    aclrtDestroyStream(st);aclrtResetDevice(0);aclFinalize(); return pass?0:1;
}}
"""
    if p == Pattern.GEMM:
        return f"""// AUTO-GENERATED differential-test harness for {name} (GEMM)
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cmath>
#include <chrono>
#include "acl/acl.h"
#include "aclrtlaunch_{name}.h"
#define CK(x) do{{aclError e=(x); if(e!=ACL_SUCCESS){{printf("ACLERR %d @%d\\n",e,__LINE__);return 2;}}}}while(0)
int main(int argc,char**argv){{
    uint32_t m=(argc>1)?(uint32_t)atol(argv[1]):512;
    uint32_t n=(argc>2)?(uint32_t)atol(argv[2]):512;
    uint32_t k=(argc>3)?(uint32_t)atol(argv[3]):512;
    int iters=(argc>4)?atoi(argv[4]):10;
    const uint32_t blockDim={sched.block_dim};
    if(m%blockDim) m=(m/blockDim)*blockDim; if(m==0)m=blockDim;
    if(n%8) n=(n/8)*8; if(n==0)n=8; if(k%8) k=(k/8)*8; if(k==0)k=8;
    float alpha=1.1f, beta=0.3f;
    size_t Ab=(size_t)m*k*4, Bb=(size_t)k*n*4, Cb=(size_t)m*n*4;
    float*Ah=(float*)malloc(Ab),*Bh=(float*)malloc(Bb),*Ch=(float*)malloc(Cb),*Co=(float*)malloc(Cb);
    for(size_t i=0;i<(size_t)m*k;i++)Ah[i]=(float)((int)(i%11)-5)*0.03f;
    for(size_t i=0;i<(size_t)k*n;i++)Bh[i]=(float)((int)(i%7)-3)*0.05f;
    for(size_t i=0;i<(size_t)m*n;i++){{Ch[i]=(float)((int)(i%5)-2)*0.1f; Co[i]=Ch[i];}}
    CK(aclInit(nullptr)); CK(aclrtSetDevice(0)); aclrtStream st; CK(aclrtCreateStream(&st));
    void*Ad,*Bd,*Cd; CK(aclrtMalloc(&Ad,Ab,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMalloc(&Bd,Bb,ACL_MEM_MALLOC_HUGE_FIRST)); CK(aclrtMalloc(&Cd,Cb,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMemcpy(Ad,Ab,Ah,Ab,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(aclrtMemcpy(Bd,Bb,Bh,Bb,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(aclrtMemcpy(Cd,Cb,Ch,Cb,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,Ad,Bd,Cd,alpha,beta,m,n,k)); CK(aclrtSynchronizeStream(st));
    CK(aclrtMemcpy(Ch,Cb,Cd,Cb,ACL_MEMCPY_DEVICE_TO_HOST)); // correctness
    double maxabs=0,maxref=0; for(uint32_t i=0;i<m;i++)for(uint32_t j=0;j<n;j++){{ double s=0;
        for(uint32_t kk=0;kk<k;kk++) s+=(double)Ah[i*k+kk]*Bh[kk*n+j];
        double r=alpha*s+beta*(double)Co[i*n+j]; double e=fabs((double)Ch[i*n+j]-r);
        if(e>maxabs)maxabs=e; if(fabs(r)>maxref)maxref=fabs(r); }}
    double maxrel=maxabs/(maxref+1e-9);
    CK(aclrtMemcpy(Cd,Cb,Co,Cb,ACL_MEMCPY_HOST_TO_DEVICE)); // reset C for timing
    auto t0=std::chrono::high_resolution_clock::now();
    for(int it=0;it<iters;it++) CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,Ad,Bd,Cd,alpha,beta,m,n,k));
    CK(aclrtSynchronizeStream(st));
    auto t1=std::chrono::high_resolution_clock::now();
    double us=std::chrono::duration<double,std::micro>(t1-t0).count()/iters;
    double gflops=2.0*(double)m*n*k/(us*1e-6)/1e9;
    int pass = maxrel < 2e-3;
    printf("RESULT op={name} pattern=gemm n=%u m=%u k=%u maxrel=%.3e pass=%d us=%.3f GFLOPs=%.2f GBps=%.2f\\n",
           n,m,k,maxrel,pass,us,gflops,0.0);
    aclrtFree(Ad);aclrtFree(Bd);aclrtFree(Cd);free(Ah);free(Bh);free(Ch);free(Co);
    aclrtDestroyStream(st);aclrtResetDevice(0);aclFinalize(); return pass?0:1;
}}
"""
    if p in (Pattern.GEMM_NT, Pattern.SYRK):
        is_syrk = (p == Pattern.SYRK)
        # SYRK: B = A, n = m (C = alpha*A*A^T + beta*C). NT: general A(m,k), B(n,k).
        setup_B = ("for(size_t i=0;i<(size_t)m*k;i++) Bh[i]=Ah[i];" if is_syrk
                   else "for(size_t i=0;i<(size_t)n*k;i++) Bh[i]=(float)((int)(i%7)-3)*0.05f;")
        force_n = "n=m;" if is_syrk else ""
        return f"""// AUTO-GENERATED differential-test harness for {name} ({p.value}, C=alpha*A*B^T+beta*C)
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cmath>
#include <chrono>
#include "acl/acl.h"
#include "aclrtlaunch_{name}.h"
#define CK(x) do{{aclError e=(x); if(e!=ACL_SUCCESS){{printf("ACLERR %d @%d\\n",e,__LINE__);return 2;}}}}while(0)
int main(int argc,char**argv){{
    uint32_t m=(argc>1)?(uint32_t)atol(argv[1]):512;
    uint32_t n=(argc>2)?(uint32_t)atol(argv[2]):512;
    uint32_t k=(argc>3)?(uint32_t)atol(argv[3]):512;
    int iters=(argc>4)?atoi(argv[4]):10;
    const uint32_t blockDim={sched.block_dim};
    if(m%blockDim) m=(m/blockDim)*blockDim; if(m==0)m=blockDim;
    if(k%64) k=(k/64)*64; if(k==0)k=64; if(n%8) n=(n/8)*8; if(n==0)n=8; {force_n}
    float alpha=1.1f, beta=0.3f;
    size_t Ab=(size_t)m*k*4, Bb=(size_t)n*k*4, Cb=(size_t)m*n*4;
    float*Ah=(float*)malloc(Ab),*Bh=(float*)malloc(Bb),*Ch=(float*)malloc(Cb),*Co=(float*)malloc(Cb);
    for(size_t i=0;i<(size_t)m*k;i++)Ah[i]=(float)((int)(i%11)-5)*0.03f;
    {setup_B}
    for(size_t i=0;i<(size_t)m*n;i++){{Ch[i]=(float)((int)(i%5)-2)*0.1f; Co[i]=Ch[i];}}
    CK(aclInit(nullptr)); CK(aclrtSetDevice(0)); aclrtStream st; CK(aclrtCreateStream(&st));
    void*Ad,*Bd,*Cd; CK(aclrtMalloc(&Ad,Ab,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMalloc(&Bd,Bb,ACL_MEM_MALLOC_HUGE_FIRST)); CK(aclrtMalloc(&Cd,Cb,ACL_MEM_MALLOC_HUGE_FIRST));
    CK(aclrtMemcpy(Ad,Ab,Ah,Ab,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(aclrtMemcpy(Bd,Bb,Bh,Bb,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(aclrtMemcpy(Cd,Cb,Ch,Cb,ACL_MEMCPY_HOST_TO_DEVICE));
    CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,Ad,Bd,Cd,alpha,beta,m,n,k)); CK(aclrtSynchronizeStream(st));
    CK(aclrtMemcpy(Ch,Cb,Cd,Cb,ACL_MEMCPY_DEVICE_TO_HOST));
    double maxabs=0,maxref=0; for(uint32_t i=0;i<m;i++)for(uint32_t j=0;j<n;j++){{ double s=0;
        for(uint32_t kk=0;kk<k;kk++) s+=(double)Ah[i*k+kk]*Bh[j*k+kk];   // A[i,:] . B[j,:]
        double r=alpha*s+beta*(double)Co[i*n+j]; double e=fabs((double)Ch[i*n+j]-r);
        if(e>maxabs)maxabs=e; if(fabs(r)>maxref)maxref=fabs(r); }}
    double maxrel=maxabs/(maxref+1e-9);
    CK(aclrtMemcpy(Cd,Cb,Co,Cb,ACL_MEMCPY_HOST_TO_DEVICE));
    auto t0=std::chrono::high_resolution_clock::now();
    for(int it=0;it<iters;it++) CK(ACLRT_LAUNCH_KERNEL({name})(blockDim,st,Ad,Bd,Cd,alpha,beta,m,n,k));
    CK(aclrtSynchronizeStream(st));
    auto t1=std::chrono::high_resolution_clock::now();
    double us=std::chrono::duration<double,std::micro>(t1-t0).count()/iters;
    double gflops=2.0*(double)m*n*k/(us*1e-6)/1e9;
    int pass = maxrel < 2e-3;
    printf("RESULT op={name} pattern={p.value} n=%u m=%u k=%u maxrel=%.3e pass=%d us=%.3f GFLOPs=%.2f GBps=%.2f\\n",
           n,m,k,maxrel,pass,us,gflops,0.0);
    aclrtFree(Ad);aclrtFree(Bd);aclrtFree(Cd);free(Ah);free(Bh);free(Ch);free(Co);
    aclrtDestroyStream(st);aclrtResetDevice(0);aclFinalize(); return pass?0:1;
}}
"""
    raise ValueError(f"emit_host: pattern {p} not yet supported")


def emit_host(air: AIR, sched: Sched) -> str:
    """Retain the archived numerical workload, rejecting unsupported dimensions."""
    import re
    text = _legacy_host(air, sched)
    text = text.replace("#include <chrono>", "#include <chrono>\n#include <cerrno>")
    parser = '''static uint32_t parse_size(const char *s) {
    if (!s || *s<'0' || *s>'9') std::exit(2);
    errno=0; char *end=nullptr; unsigned long long v=strtoull(s,&end,10);
    if(errno || *end || v==0 || v>67108864) std::exit(2);
    return (uint32_t)v;
}
'''
    text = text.replace("int main(int argc,char**argv)", parser + "int main(int argc,char**argv)")
    text = re.sub(r"\(uint32_t\)atol\((argv\[\d\])\)", r"parse_size(\1)", text)
    text = re.sub(r"atoi\((argv\[\d\])\)", r"(int)parse_size(\1)", text)
    text = text.replace("std::chrono::high_resolution_clock", "std::chrono::steady_clock")
    text = re.sub(r"    n\s*=\s*\(n/\(blockDim\*\d+\)\)\*\(blockDim\*\d+\); if\(n==0\)n=blockDim\*\d+;",
                  f"    if(n % (blockDim*{sched.tile_len})) return 2;", text)
    text = text.replace("if(n%64) n=(n/64)*64; if(n==0)n=64;", "if(n%64) return 2;")
    text = text.replace("if((m/blockDim)%8){ m=((m/blockDim)/8*8)*blockDim; } if(m==0)m=blockDim*8;",
                        "if(m%(blockDim*8)) return 2; if((4ull*n+4ull*(m/blockDim))*4+544>262144) return 2;")
    text = text.replace("if(m%blockDim) m=(m/blockDim)*blockDim; if(m==0)m=blockDim;", "if(m%blockDim) return 2;")
    text = text.replace("if(n%8) n=(n/8)*8; if(n==0)n=8;", "if(n%8) return 2;")
    text = text.replace("if(k%8) k=(k/8)*8; if(k==0)k=8;", "if(k%8) return 2; if((5ull*n+k)*4>262144) return 2;")
    text = text.replace("if(k%64) k=(k/64)*64; if(k==0)k=64;",
                        "if(k%64) return 2; if((4ull*k+3ull*n)*4+544>262144) return 2;")
    text = text.replace("; n=m;", "; if(n!=m) return 2;")
    text = text.replace("float alpha=", "if(iters<1 || iters>100000) return 2;\n    float alpha=")
    if air.s_algo.pattern == Pattern.REDUCE:
        text = text.replace("size_t bytes=", "if(iters<1 || iters>100000) return 2;\n    size_t bytes=")
    # Nonfinite candidates must fail rather than escape a max-error comparison.
    text = text.replace("double e=fabs((double)oh[i]-r)",
                        "if(!std::isfinite(oh[i]) || !std::isfinite(r)){maxrel=INFINITY;continue;} double e=fabs((double)oh[i]-r)")
    for output in ("yh[i]", "Ch[i*n+j]"):
        text = text.replace(f"double e=fabs((double){output}-r)",
                            f"if(!std::isfinite({output}) || !std::isfinite(r)){{maxabs=INFINITY;continue;}} double e=fabs((double){output}-r)")
    text = text.replace("int pass = maxrel <", "int pass = std::isfinite(maxrel) && maxrel <")
    lines = []
    for line in text.splitlines():
        names = re.findall(r"(\w+)=\(float\*\)malloc\([^;]*?\)", line)
        if names:
            # Allocation lines are complete statements, before initialization loops.
            end = line.find(";", line.find("malloc"))
            line = line[:end+1] + " if(" + "||".join("!"+n for n in names) + ")return 3;" + line[end+1:]
        lines.append(line)
    return "\n".join(lines) + "\n"


def emit_kernel(air: AIR, sched: Sched) -> str:
    if air.s_algo.pattern == Pattern.MAP:
        return emit_map_kernel(air, sched)
    if air.s_algo.pattern == Pattern.REDUCE:
        return emit_reduce_kernel(air, sched)
    if air.s_algo.pattern == Pattern.GEMV:
        return emit_gemv_kernel(air, sched)
    if air.s_algo.pattern == Pattern.GEMM:
        return emit_gemm_kernel(air, sched)
    if air.s_algo.pattern in (Pattern.GEMM_NT, Pattern.SYRK):
        return emit_gemm_nt_kernel(air, sched)
    raise ValueError(f"emit_kernel: pattern {air.s_algo.pattern} not yet supported")


def emit_project(air: AIR, sched: Sched) -> dict:
    """Return a complete project only after fresh contract and schedule checks."""
    ok, reason = guard(air)
    if not ok:
        raise ValueError(reason)
    from .schedule import check_schedule
    check_schedule(air, sched)
    return {
        f"{air.name}.cpp": emit_kernel(air, sched),
        "main.cpp": emit_host(air, sched),
        "CMakeLists.txt": CMAKE.replace("%KERNEL%", air.name).replace("%EXE%", air.name + "_bbit"),
    }
