cmake_minimum_required(VERSION 3.16)
project(ascendc_op)
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE "Release" CACHE STRING "build type" FORCE)
endif()
set(RUN_MODE "npu" CACHE STRING "run mode")
set(SOC_VERSION "Ascend310P1" CACHE STRING "soc")
set(ASCEND_CANN_PACKAGE_PATH "/usr/local/Ascend/ascend-toolkit/latest" CACHE PATH "cann")
if(CMAKE_INSTALL_PREFIX STREQUAL "/usr/local")
    set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/out" CACHE PATH "" FORCE)
endif()
if(EXISTS ${ASCEND_CANN_PACKAGE_PATH}/compiler/tikcpp/ascendc_kernel_cmake)
    set(ASCENDC_CMAKE_DIR ${ASCEND_CANN_PACKAGE_PATH}/compiler/tikcpp/ascendc_kernel_cmake)
elseif(EXISTS ${ASCEND_CANN_PACKAGE_PATH}/tools/tikcpp/ascendc_kernel_cmake)
    set(ASCENDC_CMAKE_DIR ${ASCEND_CANN_PACKAGE_PATH}/tools/tikcpp/ascendc_kernel_cmake)
else()
    set(ASCENDC_CMAKE_DIR ${ASCEND_CANN_PACKAGE_PATH}/aarch64-linux/tikcpp/ascendc_kernel_cmake)
endif()
include(${ASCENDC_CMAKE_DIR}/ascendc.cmake)
ascendc_library(ascendc_kernels_${RUN_MODE} STATIC scopy.cpp)
add_executable(scopy_bbit main.cpp)
target_compile_options(scopy_bbit PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-std=c++17>)
target_include_directories(scopy_bbit PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${ASCEND_CANN_PACKAGE_PATH}/runtime/include)
target_link_libraries(scopy_bbit PRIVATE $<BUILD_INTERFACE:host_intf_pub> ascendc_kernels_${RUN_MODE} ascendcl c_sec runtime stdc++ m)
